import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "@/components/Provider";
import { getServerSession } from "next-auth";
import { DashbaordHeader } from "@/components/DashboardHeader";
import Navigation from "@/components/Navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          <Provider session={session}>
            {session ? (
              <>
                <DashbaordHeader />
                {children}
              </>
            ) : (
              <>
                <Navigation />
                {children}
              </>
            )}
          </Provider>
        </main>
      </body>
    </html>
  );
}
